apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: nnergisyilmaz/webserver13
        name: webserver13
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: servers-config
        env:
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
        resources: {}

